kafka:
  broker: "localhost:9092"
  topic_central: "ev_central_requests"   # driver -> central
  topic_driver: "ev_central_responses"   # central -> driver
  topic_cp_commands: "ev_cp_commands"    # central -> cp (commands)
  topic_cp_data: "ev_cp_data"            # cp -> central (telemetry)
  topic_cp_status: "ev_cp_status"        # cp -> monitor/central (status/heartbeat)
cps:
  CP01:
    price_per_kwh: 0.25
    heartbeat_interval: 5
  CP02:
    price_per_kwh: 0.30
    heartbeat_interval: 5
simulation:
  charge_interval: 1
  charge_duration: 480
message_codes: {}
registry:
  host: "0.0.0.0"
  port: 8443
  base_url: "https://localhost:8443"
  cert_file: "config/certs/registry_cert.pem"
  key_file: "config/certs/registry_key.pem"
  token_ttl: 180
central_api:
  host: "0.0.0.0"
  port: 8000
  base_url: "http://localhost:8000"
security:
  credentials_dir: "config/credentials"
weather:
  polling_interval: 4
  threshold_celsius: 0
  openweather_api_key: "e5ab88092bb015fd5e95282f5a15cee8"
  default_cities:
    CP01: "Valencia,ES"
    CP02: "Madrid,ES"
    CP03: "Barcelona,ES"
    CP04: "Alicante,ES"
    CP05: "Sevilla,ES"
    CP06: "Bilbao,ES"
    CP07: "Granada,ES"
